/*
 * Copyright (c) 2026 Tomasz Zurawski
 * SPDX-License-Identifier: AGPL-3.0-only
 * https://github.com/mgrtomaszzurawski/novicloud-client-java
 */
package io.github.mgrtomaszzurawski.novicloud.demo.config;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Properties;
import java.util.StringJoiner;

/**
 * Collects soft-delete test record IDs created during CREATE_SOFT mode.
 *
 * <p>Runners call {@link #put} after creating a test record.
 * After all runners finish, the main app calls {@link #save} to persist IDs to file.
 */
public final class SoftDeleteIdsCollector {

    private static final DateTimeFormatter TIMESTAMP_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss");
    private static final String FILE_COMMENT_PREFIX = "Generated by CREATE_SOFT mode on ";
    private static final String FILE_COMMENT_SUFFIX =
            "\nDelete this file to allow CREATE_SOFT to run again.";
    private static final String SUMMARY_SEPARATOR = ", ";
    private static final String KEY_VALUE_SEPARATOR = "=";

    private final Map<String, String> entries = new LinkedHashMap<>();

    /** Stores an ID for the given endpoint key (e.g. "towary.id", "kartyloj.kod"). */
    public void put(String key, String value) {
        entries.put(key, value);
    }

    /** Saves all entries to the given file. */
    public void save(Path file) throws IOException {
        Properties props = new Properties();
        entries.forEach(props::setProperty);
        String comment = FILE_COMMENT_PREFIX + LocalDateTime.now().format(TIMESTAMP_FMT)
                + FILE_COMMENT_SUFFIX;
        try (OutputStream out = Files.newOutputStream(file)) {
            props.store(out, comment);
        }
    }

    /** Returns a summary of all stored IDs for logging. */
    public String summary() {
        StringJoiner joiner = new StringJoiner(SUMMARY_SEPARATOR);
        entries.forEach((k, v) -> joiner.add(k + KEY_VALUE_SEPARATOR + v));
        return joiner.toString();
    }

    /** Returns true if no entries have been stored. */
    public boolean isEmpty() {
        return entries.isEmpty();
    }
}
